from collections.abc import Callable

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import QtCore

class QWidget(QtCore.QObject):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def close(self) -> None: ...
    def isVisible(self) -> bool: ...
    def setGeometry(self, x: int, y: int, width: int, height: int) -> None: ...

class QDialog(QWidget):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...
    def exec_(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class QPushButton(QWidget):
    def __init__(self, text: str, parent: 'QWidget|None' = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def clicked(self, callback: 'Callable[[], None]') -> None: ...

class QLabel(QWidget):
    def __init__(self, text: str, parent: 'QWidget|None' = None) -> None: ...
    def setText(self, text: str) -> None: ...

class QLineEdit(QWidget):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...

class QGridLayout:
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...
    def addWidget(self, widget: QWidget, row: int, column: int) -> None: ...

class QMenu(QWidget):
    def __init__(self, title: str, parent: 'QWidget|None' = None) -> None: ...
    def addAction(self, text: str, callback: 'Callable[[], None]') -> None: ...

class QMenuBar(QWidget):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...
    def addMenu(self, menu: QMenu) -> None: ...
    def addAction(self, text: str, callback: 'Callable[[], None]') -> None: ...

class QComboBox(QWidget):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...

class QToolButton(QWidget):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...

class QFrame(QWidget):
    def __init__(self, parent: 'QWidget|None' = None) -> None: ...
    def setLayout(self, layout: QGridLayout) -> None: ...


