"""
Houdini hou module stubs for development.
This provides basic type hints for the hou module when developing outside Houdini.
"""

from typing import Any, Optional, Union, List, Dict

class Node:
    """Houdini node object."""
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def path(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def parm(self, name: str) -> Optional['Parm']: ...
    def parms(self) -> List['Parm']: ...
    def inputs(self) -> List[Optional['Node']]: ...
    def outputs(self) -> List['Node']: ...
    def setInput(self, input_index: int, node: Optional['Node']) -> None: ...
    def createNode(self, node_type: str, name: Optional[str] = None) -> 'Node': ...
    def children(self) -> List['Node']: ...
    def parent(self) -> Optional['Node']: ...

class Parm:
    """Houdini parameter object."""
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def eval(self) -> Any: ...
    def set(self, value: Any) -> None: ...

class GeometryNode(Node):
    """Houdini geometry (SOP) node."""
    pass

def node(path: str) -> Optional[Node]:
    """Get node by path."""
    ...

def root() -> Node:
    """Get root node."""
    ...

def pwd() -> Node:
    """Get current working directory node."""
    ...

def cd(path: str) -> None:
    """Change current directory."""
    ...

# Common node creation functions
def createNode(node_type: str, name: Optional[str] = None) -> Node:
    """Create a node at the current level."""
    ...

# Session info
def applicationName() -> str:
    """Get application name."""
    ...

def applicationVersion() -> tuple:
    """Get application version."""
    ...
