'''
Developer support functions, hython side
'''

from __future__ import annotations, _dynamic_import # noqa: F407 E261 # type: ignore


import sys
import json
import importlib.util
import inspect

import click

from zabob_houdini.houdini_bridge import invoke_houdini_function
from zabob_houdini.utils import (
    write_error_result, write_response, write_success_result,
)
from zabob_houdini.utils_dev import DEV_LAYOUT as layout, update_option_list


@click.group("_houdini_dev")
def _houdini_dev() -> None:
    """Developer support functions for hython environment."""
    pass


@_houdini_dev.command('_generate-test-list')
@click.option('--show', is_flag=True, help="List test functions to stdout.")
def _generate_test_list(show: bool) -> None:
    """
    Generate a list of test functions from the testing/ directory.

    This function:
    1. Locates the testing/ folder relative to __file__
    2. Adds that folder to sys.path
    3. Imports each file
    4. Scans each loaded module for functions beginning with '_test_'
    5. Builds a dict mapping from function name to file name
    6. Saves the dict to .vscode/tmp/test-functions.json
    7. Writes the keys of the dict, sorted, one per line to .vscode/tmp/test-functions.txt
    """

    # 1. Locate testing/ folder relative to this file
    testing = layout.testing
    vscode_tmp = layout.vscode_tmp
    if testing is None or vscode_tmp is None:
        # Silently do nothing if layout is incomplete
        return

    # 2. Add testing folder to sys.path
    testing_dir_str = str(testing)
    if testing_dir_str not in sys.path:
        sys.path.insert(0, testing_dir_str)

    # Load previous test functions to preserve entries for modules that fail to import
    json_path = vscode_tmp / "test-functions.json"
    previous_test_functions = {}
    if json_path.exists():
        try:
            with open(json_path, "r") as f:
                previous_test_functions = json.load(f)
        except Exception:
            pass  # If we can't load previous, start fresh

    # 5. Build dict mapping function name to file name
    test_functions = {}

    # 3. Import each Python file in testing/
    for py_file in sorted(testing.glob("h_*.py")):
        module_name = py_file.stem

        try:
            # Load the module
            spec: importlib.machinery.ModuleSpec | None = importlib.util.spec_from_file_location(module_name, py_file)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)  # type: ignore

                # 4. Scan for functions beginning with 'h_test_'
                for name, obj in inspect.getmembers(module, inspect.isfunction):
                    if name.startswith("h_test_"):
                        test_functions[name] = py_file.name
        except Exception as e:
            print(f"Warning: Failed to import {py_file.name}: {e}", file=sys.stderr)
            # Preserve previous test functions from this file
            for func_name, file_name in previous_test_functions.items():
                if file_name == py_file.name and func_name not in test_functions:
                    test_functions[func_name] = file_name

    # Remove tests from files that no longer exist
    existing_files = {f.name for f in testing.glob("h_*.py")}
    test_functions = {
        func_name: file_name
        for func_name, file_name in test_functions.items()
        if file_name in existing_files
    }

    # Ensure .vscode/tmp/ directory exists
    vscode_tmp.mkdir(parents=True, exist_ok=True)

    # 6. Save dict to JSON
    json_path = vscode_tmp / "test-functions.json"
    with open(json_path, "w") as f:
        json.dump(test_functions, f, indent=2, sort_keys=True)

    col_1 = max((len(name) for name in test_functions.keys()), default=10)
    col_2 = max((len(fname) for fname in test_functions.values()), default=10)
    if show:
        print(f"{'FUNCTION':<{col_1}}  {'FILE':<{col_2}}")
        print(f"{'-' * col_1}  {'-' * col_2}")

    # 7. Write sorted keys to text file, with last-used first
    update_option_list("test-functions", list(test_functions.keys()))

    # Print to stdout if requested
    if show:
        for func_name, file in sorted(test_functions.items()):
            print(f'{func_name:<{col_1}}  {file:<{col_2}}')


@_houdini_dev.command('run_test')
@click.argument('name', type=str)
def _run_test(name: str) -> None:
    """
    Run all test functions found in the testing/ directory.

    This function:
    1. Loads the test functions from the JSON file generated by _generate_test_list
    2. Executes the specified test function by name
    3. Updates test-functions.txt to put the executed test first
    """
    # Exit quietly if escape was pressed or placeholder selected
    if name in ('__escape__', '__initialize__'):
        return

    if not layout.vscode_tmp:
        return
    last = layout.vscode_tmp / "last_test.txt"
    if name == '__previous__':
        if not last.exists():
            return
        with last.open("r") as f:
            name = f.read().strip()
    else:
        with last.open("w") as f:
            f.write(name)
    json_path = layout.vscode_tmp / "test-functions.json"
    with json_path.open("r") as f:
        test_functions = json.load(f)
    if name not in test_functions:
        print(f"Test function '{name}' not found.")
        return

    # Update test-functions.txt to put this test first
    update_option_list("test-functions", list(test_functions.keys()), move_to_top=name)

    test_file = test_functions[name]
    module_name = test_file[:-3]  # Remove .py extension
    spec = importlib.util.spec_from_file_location(module_name, layout.testing / test_file)
    if spec and spec.loader:
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore
        func = getattr(module, name, None)
        if func:
            print(f"Running test: {name} from {test_file}")
            try:
                value = func()
                print("Result: ", end="", file=sys.stdout)
                write_success_result(value, _func=func, indent=True)
            except Exception as e:
                print("Result: ", end="", file=sys.stdout)
                write_error_result(f"Test '{name}' raised an exception: {e}",
                                   e,
                                   func)
                return
        else:
            print(f"Function '{name}' not found in module '{module_name}'.")


@click.command(name='_exec', hidden=True)
@click.argument('module_name')
@click.argument('function_name')
@click.argument('args', nargs=-1)
def _exec(module_name: str, function_name: str, args: tuple[str, ...]) -> None:
    """
    Internal dispatcher for hython execution.

    Usage: hython -m zabob_houdini _exec <module_name> <function_name> [args...]

    This command is hidden from help and used internally by the houdini_bridge
    to execute functions within the Houdini Python environment.
    """
    with invoke_houdini_function(module_name, function_name, args) as result:
        json.dump(result, sys.stdout)
        sys.stdout.write('\n')
        sys.stdout.flush()
        if not result["success"]:
            import os
            os._exit(1)


@click.command(name='_batch_exec', hidden=True)
def _batch_exec() -> None:
    """
    Internal batch executor for multiple hython function calls.

    Reads JSON lines from stdin, each containing:
    {"module": "module_name", "function": "function_name", "args": ["arg1", "arg2"]}

    Outputs one JSON result per line to stdout.in HoudiniResult format.

    class Location(TypedDict):
        "Location information for errors."
        file: str
        name: str
        line: int

    class HoudiniResult(TypedDict):
        "Result structure from Houdini function calls."
        success: bool
        result: NotRequired[JsonObject]
        test_location: Location
        error: NotRequired[str]
        traceback: NotRequired[str]
        error_location: NotRequired[Location | None]
    """
    import hou
    from zabob_houdini.core_node import _node_registry
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue

        # Clear state between tests to avoid leakage
        _node_registry.clear()  # Clear the node registry to avoid stale references between tests
        hou.hipFile.clear()  # Clear the current hip file to avoid stale state between tests

        # Clear imported testing modules and zabob_houdini modules (except core infrastructure)
        modules_to_remove = [
            key for key in sys.modules.keys()
            if key.startswith('testing.')
            or (key.startswith('zabob_houdini.')
                and key not in ('zabob_houdini', 'zabob_houdini.__main__',
                                'zabob_houdini.houdini_dev', 'zabob_houdini.houdini_bridge',
                                'zabob_houdini.utils', 'zabob_houdini.utils_dev'))
        ]
        for key in modules_to_remove:
            del sys.modules[key]

        # Clean up dynamic import state - remove finder and clear dyn_ modules
        from zabob_loader.dyn_loader import DynamicImportFinder
        sys.meta_path[:] = [finder for finder in sys.meta_path if not isinstance(finder, DynamicImportFinder)]

        # Re-import dyn_loader to reinstall import hooks with fresh state
        if 'zabob_loader.dyn_loader' in sys.modules:
            del sys.modules['zabob_loader.dyn_loader']
        import zabob_loader.dyn_loader  # noqa: F401
        try:
            request = json.loads(line)
        except json.JSONDecodeError as e:
            write_error_result(f'Invalid JSON in request: {e}', e)
            continue
        if 'module' not in request or 'function' not in request:
            write_error_result(f'Missing "module" or "function" field in JSON request: {request}',)
            continue
        module_name = request['module']
        function_name = request['function']
        args = request.get('args', [])
        if not isinstance(args, list):
            write_error_result(f'"args" field must be a list, got {type(args).__name__}')
            continue

        with invoke_houdini_function(module_name, function_name, args) as result:
            write_response(result)
