'''
Developer support functions, hython side
'''

from pathlib import Path
import sys
import json
import importlib.util
import inspect

import click

from zabob_houdini.utils_dev import DEV_LAYOUT as layout

@click.group("_houdini_dev")
def _houdini_dev() -> None:
    """Developer support functions for hython environment."""
    pass


@_houdini_dev.command('_generate-test-list')
@click.option('--show', is_flag=True, help="List test functions to stdout.")
def _generate_test_list(show: bool) -> None:
    """
    Generate a list of test functions from the testing/ directory.

    This function:
    1. Locates the testing/ folder relative to __file__
    2. Adds that folder to sys.path
    3. Imports each file
    4. Scans each loaded module for functions beginning with '_test_'
    5. Builds a dict mapping from function name to file name
    6. Saves the dict to .vscode/tmp/test-functions.json
    7. Writes the keys of the dict, sorted, one per line to .vscode/tmp/test-functions.txt
    """

    # 1. Locate testing/ folder relative to this file
    testing = layout.testing
    vscode_tmp = layout.vscode_tmp
    if testing is None or vscode_tmp is None:
        # Silently do nothing if layout is incomplete
        return

    # 2. Add testing folder to sys.path
    testing_dir_str = str(testing)
    if testing_dir_str not in sys.path:
        sys.path.insert(0, testing_dir_str)

    # 5. Build dict mapping function name to file name
    test_functions = {}

    # 3. Import each Python file in testing/
    for py_file in sorted(testing.glob("_*.py")):
        module_name = py_file.stem

        try:
            # Load the module
            spec = importlib.util.spec_from_file_location(module_name, py_file)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)

                # 4. Scan for functions beginning with '_test_'
                for name, obj in inspect.getmembers(module, inspect.isfunction):
                    if name.startswith("_test_"):
                        test_functions[name] = py_file.name
        except Exception as e:
            print(f"Warning: Failed to import {py_file.name}: {e}", file=sys.stderr)

    # Ensure .vscode/tmp/ directory exists
    vscode_tmp.mkdir(parents=True, exist_ok=True)

    # 6. Save dict to JSON
    json_path = vscode_tmp / "test-functions.json"
    with open(json_path, "w") as f:
        json.dump(test_functions, f, indent=2, sort_keys=True)

    col_1 = max((len(name) for name in test_functions.keys()), default=10)
    col_2 = max((len(fname) for fname in test_functions.values()), default=10)
    if show:
       print(f"{'FUNCTION':<{col_1}}  {'FILE':<{col_2}}")
       print(f"{'-' * col_1}  {'-' * col_2}")

    # 7. Write sorted keys to text file
    txt_path = vscode_tmp / "test-functions.txt"
    with open(txt_path, "w") as f:
        for func_name, file in sorted(test_functions.items()):
            if show:
                print(f'{func_name:<{col_1}}  {file:<{col_2}}')
            f.write(f"{func_name}\n")


@_houdini_dev.command('run_test')
@click.argument('name', type=str)
def _run_test(name: str) -> None:
    """
    Run all test functions found in the testing/ directory.

    This function:
    1. Loads the test functions from the JSON file generated by _generate_test_list
    2. Executes each test function
    3. Optionally lists the test functions being run
    """
    if not layout.vscode_tmp:
        return
    json_path = layout.vscode_tmp / "test-functions.json"
    with json_path.open("r") as f:
        test_functions = json.load(f)
    if name not in test_functions:
        print(f"Test function '{name}' not found.")
        return
    test_file = test_functions[name]
    module_name = test_file[:-3]  # Remove .py extension
    spec = importlib.util.spec_from_file_location(module_name, layout.testing / test_file)
    if spec and spec.loader:
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        func = getattr(module, name, None)
        if func:
            print(f"Running test: {name} from {test_file}")
            func()
        else:
            print(f"Function '{name}' not found in module '{module_name}'.")

