"""Clone process management module for Houdini rendering clones.

See https://www.sidefx.com/docs/houdini/hom/hou/clone/
"""

from typing import Any, Callable

import hou

class Connection:
    """Represents a connection to a clone process.

    These objects represent an active or potential connection to a Houdini clone
    process, either on the local machine or a remote machine. A connection can be
    connected and disconnected repeatedly, but the object continues to be valid.

    Clone connections are identified by a unique session id string which behaves
    much like a Houdini node name. At any given time, the session id for each clone
    connection is unique. But session ids can be reused if a connection is deleted and
    a new one created.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html
    """

    # Connection Validity and Identification

    def isValid(self) -> bool:
        """Return True if the connection associated with this object is still valid.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#isValid
        """
        ...

    def sessionId(self) -> str:
        """Return the unique string that can be used to identify this connection object.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#sessionId
        """
        ...

    def name(self) -> str:
        """Return the user-facing name for this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#name
        """
        ...

    def setName(self, name: str) -> None:
        """Set the user-facing name for this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setName
        """
        ...

    # LOP and Camera Configuration

    def lopNode(self) -> hou.LopNode:
        """Return the LOP node that defines the stage which will be rendered by this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#lopNode
        """
        ...

    def setLopNode(self, lop: hou.LopNode) -> None:
        """Set the LOP node that defines the stage which will be rendered by this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setLopNode
        """
        ...

    def cameraPath(self) -> str:
        """Return the USD primitive path of the camera prim that defines the view.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#cameraPath
        """
        ...

    def setCameraPath(self, camerapath: str) -> None:
        """Set the USD primitive path of the camera prim that defines the view.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setCameraPath
        """
        ...

    # Renderer Configuration

    def renderer(self) -> str:
        """Return the name of the Render Delegate this clone will use.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#renderer
        """
        ...

    def setRenderer(self, renderer: str) -> None:
        """Set the name of the Render Delegate this clone will use.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setRenderer
        """
        ...

    def renderSettings(self) -> str:
        """Return the USD primitive path of the render settings prim.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#renderSettings
        """
        ...

    def setRenderSettings(self, rendersettings: str) -> None:
        """Set the USD primitive path of the render settings prim.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setRenderSettings
        """
        ...

    def renderPass(self) -> str:
        """Return the USD primitive path of the render pass prim.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#renderPass
        """
        ...

    def setRenderPass(self, renderpass: str) -> None:
        """Set the USD primitive path of the render pass prim.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setRenderPass
        """
        ...

    # AOV Configuration

    def availableAovs(self) -> tuple[str, ...]:
        """Return the names of all AOVs generated by the clone render.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#availableAovs
        """
        ...

    def displayAov(self) -> str:
        """Return the name of the AOV this clone should return to the host.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#displayAov
        """
        ...

    def setDisplayAov(self, aov: str) -> None:
        """Set the name of the AOV this clone should return to the host.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setDisplayAov
        """
        ...

    # Resolution Configuration

    def resolutionScale(self) -> float:
        """Return the override resolution scale factor.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#resolutionScale
        """
        ...

    def setResolutionScale(self, resolution_scale: float) -> None:
        """Set the resolution scale for the image generated by this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setResolutionScale
        """
        ...

    def resolution(self) -> tuple[int, int]:
        """Return the override resolution set for the clone's returned image.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#resolution
        """
        ...

    def setResolution(self, width: int, height: int) -> None:
        """Set the resolution of the image generated by this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setResolution
        """
        ...

    def renderRegion(self) -> hou.Vector4:
        """Return the render region set for the clone's returned image.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#renderRegion
        """
        ...

    def setRenderRegion(self, render_region: hou.Vector4) -> None:
        """Set the render region of the image generated by this clone.

        The render_region is of the form (x0, y0, x1, y1).

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setRenderRegion
        """
        ...

    # Context and Frame Configuration

    def frameExpression(self) -> str:
        """Return the expression that generates the frame for this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#frameExpression
        """
        ...

    def setFrameExpression(self, expression: str) -> None:
        """Set the expression that generates the frame for this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setFrameExpression
        """
        ...

    def contextOptionExpression(self, opt: str) -> str:
        """Return the expression that generates the value for context option opt.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#contextOptionExpression
        """
        ...

    def setContextOptionExpression(self, opt: str, expression: str) -> None:
        """Set the expression that generates the value for context option opt.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setContextOptionExpression
        """
        ...

    def contextOptionsWithExpressions(self) -> tuple[str, ...]:
        """Return a tuple of context option names that have expressions set.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#contextOptionsWithExpressions
        """
        ...

    # Update Configuration

    def setProcessUpdates(self, process_updates: bool) -> None:
        """Configure whether the clone process responds to updates from the host.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setProcessUpdates
        """
        ...

    def processUpdates(self) -> bool:
        """Return whether the clone will restart its render in response to updates.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#processUpdates
        """
        ...

    # Launcher Configuration

    def setLauncherConfig(self, config: dict[str, Any]) -> None:
        """Store the dictionary of launcher configuration options for this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setLauncherConfig
        """
        ...

    def launcherConfig(self) -> dict[str, Any]:
        """Return a dictionary of launcher configuration options for this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#launcherConfig
        """
        ...

    # Connection Management

    def connect(self, host: str, port: int) -> bool:
        """Connect this host to a running clone process on the specified machine.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#connect
        """
        ...

    def isConnected(self) -> bool:
        """Return true if this connection represents an active connection to a clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#isConnected
        """
        ...

    def host(self) -> str:
        """Return the name of the host machine on which the clone process is running.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#host
        """
        ...

    def port(self) -> int:
        """Return the port number used to connect to this clone process.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#port
        """
        ...

    def setWaitingToConnect(self, waiting_to_connect: bool) -> None:
        """Set a flag indicating that this connection is waiting to connect.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#setWaitingToConnect
        """
        ...

    def isWaitingToConnect(self) -> bool:
        """Return true if setWaitingToConnect(True) has been called.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#isWaitingToConnect
        """
        ...

    def disconnect(self) -> None:
        """Disconnect from a connected clone process.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#disconnect
        """
        ...

    # Image Management

    def imagePath(self) -> str:
        """Return a string that can be used to access the most recent image from clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#imagePath
        """
        ...

    def imageSize(self) -> tuple[int, int]:
        """Return the width and height of the most recent image from this clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#imageSize
        """
        ...

    def imageVersion(self) -> int:
        """Return a number that increases every time a new image is sent by the clone.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#imageVersion
        """
        ...

    def percentComplete(self) -> float:
        """Return the progress of the render as reported through render statistics.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#percentComplete
        """
        ...

    # Gallery Management

    def renderGalleryDataSource(self) -> hou.AssetGalleryDataSource:
        """Return the snapshot gallery data source for the target LOP Network.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#renderGalleryDataSource
        """
        ...

    def renderGalleryItemId(self) -> str:
        """Return the gallery item ID for the current render snapshot.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#renderGalleryItemId
        """
        ...

    def createSnapshot(self) -> str:
        """Create a snapshot in the LOP Network's snapshot gallery database.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#createSnapshot
        """
        ...

    # Duplication

    def duplicate(self) -> Connection:
        """Make a copy of this clone object.

        See https://www.sidefx.com/docs/houdini/hom/hou/clone/Connection.html#duplicate
        """
        ...

# Module-level Functions

def clone(session_id: str) -> Connection:
    """Return the clone connection with the specified session ID.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/clone.html
    """
    ...

def clones() -> tuple[Connection, ...]:
    """Return a tuple of all clone connections.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/clones.html
    """
    ...

def createClone() -> Connection:
    """Create a new clone connection object.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/createClone.html
    """
    ...

def deleteClone(connection: Connection) -> None:
    """Delete the specified clone connection.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/deleteClone.html
    """
    ...

def deleteDisconnectedClones() -> None:
    """Delete all disconnected clone connections.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/deleteDisconnectedClones.html
    """
    ...

# Connection Callbacks

def addConnectionChangeCallback(callback: Callable[[Connection], Any]) -> None:
    """Add a callback for when clone connections are added, removed, or modified.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/addConnectionChangeCallback.html
    """
    ...

def connectionChangeCallbacks() -> tuple[Callable[[Connection], Any], ...]:
    """Return a tuple of all registered connection change callbacks.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/connectionChangeCallbacks.html
    """
    ...

def removeConnectionChangeCallback(callback: Callable[[Connection], Any]) -> None:
    """Remove a previously registered connection change callback.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/removeConnectionChangeCallback.html
    """
    ...

def removeAllConnectionChangeCallbacks() -> None:
    """Remove all registered connection change callbacks.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/removeAllConnectionChangeCallbacks.html
    """
    ...

# Image Callbacks

def addImageChangeCallback(callback: Callable[[Connection], Any]) -> None:
    """Add a callback for when a clone sends a new image to the host.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/addImageChangeCallback.html
    """
    ...

def imageChangeCallbacks() -> tuple[Callable[[Connection], Any], ...]:
    """Return a tuple of all registered image change callbacks.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/imageChangeCallbacks.html
    """
    ...

def removeImageChangeCallback(callback: Callable[[Connection], Any]) -> None:
    """Remove a previously registered image change callback.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/removeImageChangeCallback.html
    """
    ...

def removeAllImageChangeCallbacks() -> None:
    """Remove all registered image change callbacks.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/removeAllImageChangeCallbacks.html
    """
    ...

# Process Lifecycle

def isRunningAsClone() -> bool:
    """Return True if the current process is running as a clone.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/isRunningAsClone.html
    """
    ...

def runAsClone() -> None:
    """Run the current process as a clone.

    See https://www.sidefx.com/docs/houdini/hom/hou/clone/runAsClone.html
    """
    ...
