"""
LOP module for Houdini USD/Solaris workflow utilities.

This module provides functions for working with USD stages, preferences,
shader translation, parameters, render delegates, and output processors.

See: https://www.sidefx.com/docs/houdini/hom/hou/lop.html
"""

from typing import Any

import hou

# ============================================================================
# Preferences
# ============================================================================

def defaultNewPrimPath() -> str:
    """
    Return the USD primitive path that will be used by default on new LOP nodes
    with a primpath parameter with a default of /$OS.
    """
    ...

def setDefaultNewPrimPath(path: str) -> None:
    """
    Set the USD primitive path that will be used by default on new LOP nodes
    with a primpath parameter with a default of /$OS.

    Args:
        path: The default primitive path to use
    """
    ...

def defaultCollectionsPrimPath() -> str:
    """
    Return the USD primitive path that will be used as the default location
    when creating new collections.
    """
    ...

def setDefaultCollectionsPrimPath(path: str) -> None:
    """
    Set the USD primitive path that will be used as the default location
    when creating new collections.

    Args:
        path: The default collections primitive path
    """
    ...

def defaultCollectionsPrimType() -> str:
    """
    Return the USD primitive type that will be created for holding collections
    when the destination primitive doesn't already exist.
    """
    ...

def setDefaultCollectionsPrimType(prim_type: str) -> None:
    """
    Set the USD primitive type that will be created for holding collections
    when the destination primitive doesn't already exist.

    Args:
        prim_type: The primitive type for collections
    """
    ...

def defaultLightsPrimPath() -> str:
    """
    Return the USD primitive path that will be used as the default location
    when creating new lights.
    """
    ...

def setDefaultLightsPrimPath(path: str) -> None:
    """
    Set the USD primitive path that will be used as the default location
    when creating new lights.

    Args:
        path: The default lights primitive path
    """
    ...

def defaultCamerasPrimPath() -> str:
    """
    Return the USD primitive path that will be used as the default location
    when creating new cameras.
    """
    ...

def setDefaultCamerasPrimPath(path: str) -> None:
    """
    Set the USD primitive path that will be used as the default location
    when creating new cameras.

    Args:
        path: The default cameras primitive path
    """
    ...

def defaultTransformSuffix() -> str:
    """
    Return the string that will be used as the default suffix on transform
    attribute names.
    """
    ...

def setDefaultTransformSuffix(suffix: str) -> None:
    """
    Set the string that will be used as the default suffix on transform
    attribute names.

    Args:
        suffix: The transform attribute suffix
    """
    ...

def showResolvedPaths() -> bool:
    """
    Return True if the option to show resolved layer file paths is turned on.
    """
    ...

def setShowResolvedPaths(show_resolved_paths: bool) -> None:
    """
    Set the option to control whether panels that show layer file paths should
    display the exact path set on the layer, or the path after passing it through
    the USD path resolver.

    Args:
        show_resolved_paths: True to show resolved paths
    """
    ...

def panesFollowCurrentNode() -> bool:
    """
    Return True if LOP panes such as the Scene Graph Tree and Scene Graph Details
    should follow the current node selected in the network editor.
    """
    ...

def setPanesFollowCurrentNode(follow_current_node: bool) -> None:
    """
    Set the option for LOP panes such as the Scene Graph Tree and Scene Graph
    Details to follow the current node selected in the network editor.

    Args:
        follow_current_node: True to follow current node
    """
    ...

def panesShowViewportStage() -> bool:
    """
    Return True if LOP panes such as the Scene Graph Tree and Scene Graph Details
    should show information about the USD stage generated by applying any viewport
    overrides set in the Scene Graph Tree.
    """
    ...

def setPanesShowViewportStage(show_viewport_stage: bool) -> None:
    """
    Set the option for LOP panes such as the Scene Graph Tree and Scene Graph
    Details to show information about the USD stage generated by applying any
    viewport overrides set in the Scene Graph Tree.

    Args:
        show_viewport_stage: True to show viewport stage
    """
    ...

def panesShowPostLayers() -> bool:
    """
    Return True if LOP panes such as the Scene Graph Tree and Scene Graph Details
    should show information about the USD stage generated by applying any post-layers
    applied to the parent LOP Network.
    """
    ...

def setPanesShowPostLayers(show_post_layers: bool) -> None:
    """
    Set the option for LOP panes such as the Scene Graph Tree and Scene Graph
    Details to show information about the USD stage generated by applying any
    post-layers applied to the parent LOP Network.

    Args:
        show_post_layers: True to show post layers
    """
    ...

def autoSetAssetResolverContext() -> bool:
    """
    Return True if the Sublayer and Reference LOP nodes should automatically use
    their first USD layer loaded from disk as the resolver context asset path passed
    to the USD stage to define its asset resolver context.
    """
    ...

def setAutoSetAssetResolverContext(auto_set_context: bool) -> None:
    """
    Pass in a value of True if the Sublayer and Reference LOP nodes should
    automatically use their first USD layer loaded from disk as the resolver context
    asset path passed to the USD stage to define its asset resolver context.

    Args:
        auto_set_context: True to auto-set resolver context
    """
    ...

def updateRendererInBackground() -> bool:
    """
    Return True if the LOP viewport has been configured to run update tasks in
    the background.
    """
    ...

def setUpdateRendererInBackground(update_in_background: bool) -> None:
    """
    Pass in a value of True to cause the LOP viewport to run update tasks in the
    background, which results in better interactivity but allows the viewport display
    to be temporarily out of sync with the current cooked LOP stage.

    Args:
        update_in_background: True to update in background
    """
    ...

def loadPayloadsByDefault() -> bool:
    """
    Return True if new LOP Networks will be created with the option to load all
    payloads in the viewport enabled.
    """
    ...

def setLoadPayloadsByDefault(load_payloads: bool) -> None:
    """
    Pass in a value of True to cause new LOP Networks to be created with the option
    to load all payloads in the viewport enabled.

    Args:
        load_payloads: True to load payloads by default
    """
    ...

def allowViewportOnlyPayloads() -> bool:
    """
    Return True if the scene graph tree can allow the user to force the loading of
    a payload into the viewport which has been prevented from loading by a Configure
    Stage node.
    """
    ...

def setAllowViewportOnlyPayloads(allow_viewport_only_payloads: bool) -> None:
    """
    Set the flag that indicates whether the viewport is allowed to load payloads
    that have been specified as unloaded by a Configure Stage node.

    Args:
        allow_viewport_only_payloads: True to allow viewport-only payloads
    """
    ...

def pathParameterCompletion() -> bool:
    """
    Return True if USD Primitive Path parameters should provide syntax highlighting
    and prim path completion hints.
    """
    ...

def setPathParameterCompletion(path_parameter_completion: bool) -> None:
    """
    Set the flag that indicates whether the USD Primitive Path parameters should
    provide path completion hints.

    Args:
        path_parameter_completion: True to enable path completion
    """
    ...

def defaultMetersPerUnit() -> float:
    """
    Return the default meters per unit metric that will be saved into USD layers
    that do not have this value explicitly set.
    """
    ...

def setDefaultMetersPerUnit(meters_per_unit: float) -> None:
    """
    Set the default meters per unit metric that will be saved into USD layers that
    do not have this value explicitly set.

    Args:
        meters_per_unit: The meters per unit value
    """
    ...

def defaultUpAxis() -> str:
    """
    Return the default up axis value that will be saved into USD layers that do not
    have this value explicitly set.
    """
    ...

def setDefaultUpAxis(up_axis: str) -> None:
    """
    Set the default up axis that will be saved into USD layers that do not have this
    value explicitly set.

    Args:
        up_axis: The up axis value (e.g., "Y" or "Z")
    """
    ...

def savePreferences() -> bool:
    """
    Saves out the current LOP preferences to $HOME/houdiniX.Y/solaris.pref.

    Returns:
        True if successful
    """
    ...

def addPreferenceChangeCallback(callback: Any) -> None:
    """
    Registers a callback function that is invoked any time one of the LOP preferences
    is changed.

    Args:
        callback: Callable to be invoked on preference changes
    """
    ...

def removePreferenceChangeCallback(callback: Any) -> None:
    """
    Deregisters a callback function previously registered with a call to
    addPreferenceChangeCallback.

    Args:
        callback: The callback to remove
    """
    ...

# ============================================================================
# VOP to UsdShade Translation
# ============================================================================

def shaderTranslatorID(node: hou.Node) -> int:
    """
    Returns the ID of the shader translator for the given node.

    Args:
        node: The shader node

    Returns:
        The shader translator ID
    """
    ...

def shaderRenderContextName(node: hou.Node, node_output_name: str) -> str:
    """
    Returns the render context name for the given node and output.

    Args:
        node: The shader node
        node_output_name: The output name on the node

    Returns:
        The render context name
    """
    ...

def translateShader(
    node: hou.Node,
    node_output_name: str,
    material_prim_path: str,
    container_prim_path: str,
    shader_prim_name: str | None = None,
    frame: float | None = None,
) -> str:
    """
    Creates a new shader primitive and returns a path to the shader primitive output.

    Args:
        node: The shader node to translate
        node_output_name: The output name on the node
        material_prim_path: The USD path for the material primitive
        container_prim_path: The USD path for the container primitive
        shader_prim_name: Optional name for the shader primitive
        frame: Optional frame time for evaluation

    Returns:
        The path to the shader primitive output
    """
    ...

def reportShaderTranslation(node: hou.Node, usd_shader_path: str) -> None:
    """
    Adds an entry to the table of known shader translations.

    Args:
        node: The shader node
        usd_shader_path: The USD path to the translated shader
    """
    ...

def shaderNodeType(shader_name: str) -> hou.NodeType:
    """
    Returns a shader hou.NodeType given the shader name.

    Args:
        shader_name: The name of the shader

    Returns:
        The node type for the shader
    """
    ...

# ============================================================================
# Node Parameters and USD Properties
# ============================================================================

def createParmsForProperty(
    source: Any,
    primpath: str,
    propertyname: str,
    parametername: str,
    prepend_control_parm: bool,
    prefix_xform_parms: bool,
) -> hou.ParmTemplateGroup:
    """
    Given a property on a USD stage, this method returns a hou.ParmTemplateGroup
    object that describes the parameters that can be placed on an Edit Properties LOP
    node to control that USD property.

    Args:
        source: The source USD stage or node
        primpath: The primitive path
        propertyname: The property name
        parametername: The parameter name to create
        prepend_control_parm: Whether to prepend a control parameter
        prefix_xform_parms: Whether to prefix transform parameters

    Returns:
        A parameter template group
    """
    ...

def createParmsForParameter(
    source: Any,
    parametername: str,
    usdvaluetype: str,
    prepend_control_parm: bool,
    propertyname: str,
) -> hou.ParmTemplateGroup:
    """
    Given a source node parameter, this method returns a hou.ParmTemplateGroup
    object that describes the parameters that can be placed on an Edit Properties LOP
    node to control a value of a corresponding USD property.

    Args:
        source: The source node
        parametername: The parameter name
        usdvaluetype: The USD value type
        prepend_control_parm: Whether to prepend a control parameter
        propertyname: The USD property name

    Returns:
        A parameter template group
    """
    ...

def createConnectionParmsForProperty(
    source: Any,
    primpath: str,
    propertyname: str,
    parametername: str | None = None,
    prepend_control_parm: bool = True,
) -> hou.ParmTemplateGroup:
    """
    Given a property on a USD stage, this method returns a hou.ParmTemplateGroup
    object that describes the parameters that can be placed on an Edit Properties LOP
    node to modify the connection of that USD (destination) property to a source
    attribute.

    Args:
        source: The source USD stage or node
        primpath: The primitive path
        propertyname: The property name
        parametername: Optional parameter name to create
        prepend_control_parm: Whether to prepend a control parameter

    Returns:
        A parameter template group
    """
    ...

def setParmTupleFromProperty(
    parmtuple: hou.ParmTuple,
    source: Any,
    primpath: str,
    propertyname: str,
) -> None:
    """
    Set the value of a node parameter tuple from the value of a property on a USD
    primitive.

    Args:
        parmtuple: The parameter tuple to set
        source: The source USD stage or node
        primpath: The primitive path
        propertyname: The property name
    """
    ...

def stageVariableExpression(expr: str) -> str:
    """
    This helper method makes it easier to author stage variable expressions for use
    in USD files.

    Args:
        expr: The expression to convert

    Returns:
        The stage variable expression string
    """
    ...

def sve(expr: str) -> str:
    """
    This method is simply a shorter alias for the stageVariableExpression method.

    Args:
        expr: The expression to convert

    Returns:
        The stage variable expression string
    """
    ...

# ============================================================================
# Render Delegate Information
# ============================================================================

def availableRendererInfo() -> list[dict[str, Any]]:
    """
    Returns a list of dicts containing meta data for registered renderer plugins.

    Returns:
        List of dictionaries with renderer information
    """
    ...

def availableRendererLabels() -> tuple[str, ...]:
    """
    Returns a tuple with the display labels of registered renderer plugins.

    Returns:
        Tuple of renderer display labels
    """
    ...

def availableRendererNames() -> tuple[str, ...]:
    """
    Returns a tuple with the internal names of registered renderer plugins.

    Returns:
        Tuple of renderer internal names
    """
    ...

# ============================================================================
# Output Processors
# ============================================================================

def outputProcessorParms(name: str) -> hou.ParmTemplateGroup:
    """
    Returns the parameters that can be used to configure the output processor with
    an internal name that matches the name parameter.

    Args:
        name: The internal name of the output processor

    Returns:
        Parameter template group for the output processor
    """
    ...

def outputProcessors() -> tuple[tuple[str, str], ...]:
    """
    Returns a tuple holding the internal name and user facing label for each output
    processor plugin in the registry.

    Returns:
        Tuple of (internal_name, label) tuples
    """
    ...

# ============================================================================
# USD General
# ============================================================================

def makeValidPrimName(name: str) -> str:
    """
    This function ensures that a string meets the requirements of a legal USD
    primitive name that can be used as part of a valid primitive path.

    Args:
        name: The name to validate

    Returns:
        A valid USD primitive name
    """
    ...

def makeValidPrimPath(path: str, allow_relative: bool = False) -> str:
    """
    This function ensures that a string meets the requirements of a legal USD
    primitive path that can be converted into a psx.Sdf.Path object.

    Args:
        path: The path to validate
        allow_relative: Whether to allow relative paths

    Returns:
        A valid USD primitive path
    """
    ...

def reloadLayer(layer_path: str, recursive: bool = False) -> None:
    """
    This method calls the USD Reload method for the specified layer path.

    Args:
        layer_path: The path to the layer to reload
        recursive: Whether to reload recursively
    """
    ...

def usdVersionInfo() -> dict[str, str]:
    """
    Returns a dictionary holding information about the USD library built into
    Houdini.

    Returns:
        Dictionary with USD version information
    """
    ...

def usdOutputMinimumSeverity() -> Any:
    """
    Returns the minimum USD message severity that will be output to standard output.

    Returns:
        The minimum severity (should be hou.severityType value)
    """
    ...

def setUsdOutputMinimumSeverity(severity: Any) -> None:
    """
    Sets the minimum message severity produced by the USD library that should be
    written to standard output.

    Args:
        severity: The minimum severity (should be hou.severityType value)
    """
    ...

def addLockedGeometry(identifier: str, geo: hou.Geometry, args: dict[str, Any] = {}) -> str:
    """
    Adds a locked copy of a hou.Geometry to a registry, so that it can be used as a
    USD reference or sublayer.

    Args:
        identifier: The identifier for the locked geometry
        geo: The geometry to lock
        args: Optional arguments dictionary

    Returns:
        The identifier of the locked geometry
    """
    ...

def removeLockedGeometry(identifier: str) -> bool:
    """
    Removes a locked hou.Geometry from the registry, returning a bool to indicate
    success or failure.

    Args:
        identifier: The identifier of the locked geometry to remove

    Returns:
        True if successful, False otherwise
    """
    ...

def forceReloadAllFilesFromDisk(reload_viewports: bool) -> None:
    """
    Presses the reload button on every LOP node with such a parameter.

    Args:
        reload_viewports: Whether to reload viewports as well
    """
    ...

def mutingIdentifier(identifier: str) -> str:
    """
    Return the identifier that will be returned by
    hou.LopViewportLoadMasks.muteLayers when muting a USD layer authored by a LOP node.

    Args:
        identifier: The layer identifier

    Returns:
        The muting identifier
    """
    ...
